# Generated by Django 3.0.6 on 2020-08-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=15)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_text', models.CharField(max_length=300)),
                ('event_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
