# Generated by Django 3.0.6 on 2020-08-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='event_image',
            new_name='post_image',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_title',
            field=models.CharField(max_length=300),
        ),
    ]
